### PR TITLE
Fix typo on package import

### PR DESCRIPTION
**Pull request by Christopher-Hayes**
This was a fix made to the package 2 years ago - https://github.com/BuilderIO/builder/commit/aa71b80c77766c12a3f4704a0c740f2498de7b57

### CODE REVIEW

**Comment by steve8708** [comment]
thanks @Christopher-Hayes! Looks like we just need to update that package to the latest (otherwise build breaks) and we can merge this in 
image

**Comment by Christopher-Hayes** [comment]
Oh right, thanks @steve8708.

Updated the version. Ran `yarn` to keep the `yarn.lock` in sync, yarn's linter changed some of the `package.json` line formatting just as an FYI.

**Comment by steve8708** [comment]
looks great, thanks so much @Christopher-Hayes !

**Comment by Christopher-Hayes** [comment]
**Sidenote** - this demo may still not work until the PR on the personalization-utils package is merged: https://github.com/BuilderIO/builder/issues/1679

I'm on Next v13, and I had to monkey patch `request.cookies.entries = <function>` into my code to get the personalziation-utils package working.

**Comment by steve8708** [comment]
ah! what PR are you referring to? that links to an issue but i'm not seeing a PR connected to it

**Comment by Christopher-Hayes** [comment]
mb @steve8708, looking into it now, actually **it was fixed and merged** in 2023, here's the PR: https://github.com/BuilderIO/builder/pull/1847

But the PR had a breaking change, so a new major release was planned, but has not been released yet.

In the short-term this builder demo could be fixed by switching to the [dev release (v2.0.1-0)](https://www.npmjs.com/package/@builder.io/personalization-utils/v/2.0.1-0) of the personalization-utils library.

**Pull request merged**
